title = "Curiosity Blog"
subtitle = "Stay up to date with the latest activity!"
author = "Curiosity Team"
linkPrefix = "/Curiosity-Blog"
github = "https://github.com/oskikiboy"
twitter = "https://twitter.com/DEV_Curiosity"
facebook = ""
googleplus = ""
linkedin = ""
